using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class collectBox : MonoBehaviour
{

    public winBoxController box;
    public bool istriggered;
    // Start is called before the first frame update
    void Start()
    {
        istriggered = false;
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.tag == "Player" && !istriggered)
        {
            Destroy(this.gameObject);
            istriggered = true;
            box.open();
        }
    }
}
